python3 Rebalance-Xenoblade2.py -single "UnpackedBDAT/common_ms/common_ms/fld_randomtalk.json" -mode 2
python3 Rebalance-Xenoblade2.py -single "UnpackedBDAT/common_ms/common_ms/autotalk_ma03.json" -mode 2
python3 Rebalance-Xenoblade2.py -single "UnpackedBDAT/common_ms/common_ms/autotalk_ma05.json" -mode 2
python3 Rebalance-Xenoblade2.py -single "UnpackedBDAT/common_ms/common_ms/autotalk_ma07.json" -mode 2
python3 Rebalance-Xenoblade2.py -single "UnpackedBDAT/common_ms/common_ms/autotalk_ma08.json" -mode 2
python3 Rebalance-Xenoblade2.py -single "UnpackedBDAT/common_ms/common_ms/autotalk_ma10.json" -mode 2
python3 Rebalance-Xenoblade2.py -single "UnpackedBDAT/common_ms/common_ms/autotalk_ma11.json" -mode 2
python3 Rebalance-Xenoblade2.py -single "UnpackedBDAT/common_ms/common_ms/autotalk_ma15.json" -mode 2
python3 Rebalance-Xenoblade2.py -single "UnpackedBDAT/common_ms/common_ms/autotalk_ma40.json" -mode 2
python3 Rebalance-Xenoblade2.py -single "UnpackedBDAT/common_ms/common_ms/autotalk_ma41.json" -mode 2
